### PR TITLE
Fix language loading + fix file inclusion & css/js enqueueing for non…

### PR DESCRIPTION
**Pull request by jrfnl**
…-standard directory setups.

Combines the proposed fixes from #40 and #41 (plus two more directory paths missed in the earlier PR).

As requested https://github.com/jfarthing84/theme-my-login/pull/40#issuecomment-164848466

### CODE REVIEW

**Comment by jfarthing84** [comment]
I'd rather the constant name be THEME_MY_LOGIN_PATH. Also, I'd prefer two separate commits for that and the language loading, with the commit messages first line no longer than 72 characters.

Also, the `language` directory will now be called <del>`langauges`</del> `languages`.

**Comment by jrfnl** [comment]
From your earlier comment, you gave the impression that you wanted 1 PR combining both which is what you have now.
I would appreciate it if you made it clear what you want changed in one go. Would save me reworking the PR three of four times... it's not as if I got time to spare...

> Also, the language directory will now be called langauges.

I'm going to presume you don't want the spelling mistake in the lang directory.

**Comment by jfarthing84** [comment]
I just clarified that in the comment [above](https://github.com/jfarthing84/theme-my-login/pull/48#issuecomment-167680740). If you'd rather, I can close the pull request and implement myself.

Of course I don't want the spelling mistake.

**Comment by jrfnl** [comment]
> I just clarified that in the comment above.

After I'd already reworked the PR from 2 to 1, so now I'm going to have to do it again.

> If you'd rather, I can close the pull request and implement myself.

That's not the point. I'm asking you to show me the courtesy of being respectful of my time and giving me the changes you want in one go, rather than in two, three installments.

**Comment by jfarthing84** [comment]
Please note, I never asked for contributions. But thank you for your time!

**Comment by jrfnl** [comment]
> Please note, I never asked for contributions.

Fair enough, I suggest you make the project close source in that case and remove it from the WP directory.
It is _implicit_ in the nature of an open source project with a GPL license that constructive contributions are welcome. Just like putting in as an open project on GH sends the same message.

It is not as if this is a new feature I'm suggesting or anything. It's two bug fixes for things which really weren't working as they should.

**Comment by jrfnl** [comment]
Anyways, all done now (again).
Split the PR into two commits and did some extra code review which still caught an issue with the code (luckily).

Also added an extra commit which does the 'no pass by reference' change for the modules. Seemed some files weren't open when I originally made that change, so I'd missed some.

**Pull request merged**
