### PR TITLE
Fix file loading for non-standard directory setups.

### PR DESCRIPTION
**Pull request by jrfnl**
While debugging the language issue, I added the plugin to my local test environment using a non-standard path and literally _everything_ broke. I couldn't even activate the plugin because of the errors.

This PR fixes that.

### CODE REVIEW

**Comment by jfarthing84** [comment]
This is something that will be addressed, differently, in 7.0. I don't want to introduce a new constant, only to remove it later.

**Comment by jrfnl** [comment]
While I appreciate that it will be addressed at _some point in the future_, in the mean time translations are not loading and non-standard paths are completely broken.

The constant is only there to DRY things out. Can easily be removed and instead have that same `dirname( __FILE__ )` snippet everywhere it's needed.

Considering the number of versions which have had problems with language files loading and the solution I'm offering working, I'm a bit peeved you dismiss these two PRs so easily.

**Comment by jfarthing84** [comment]
Just fixed the language issue in 2e171a73f587ff3fc6a415d31b1ff1df4098492a. What kind of non-standard paths are being utilized?

**Comment by jrfnl** [comment]
> Just fixed the language issue in 2e171a7.

Unfortunately, no, you haven't fixed it and you have added more redundancy instead. Please look at my PR carefully to see how it can be fixed properly.

> What kind of non-standard paths are being utilized?

Uploading the plugin in a differently named directory like `/wp-plugins/theme--login-6.4.2/`.

**Comment by jfarthing84** [comment]
So you're telling me that the way bbPress loads it's language files is incorrect? Because it's exactly the same as what I did.

**Comment by jrfnl** [comment]
Comparing this plugin with bbPress is like comparing apples with a bloody big forest of pear trees. Not the same thing at all. bbPress hijacks a lot of WP, your plugin is (luckily) by far not that invasive.

And yes, it's incorrect considering this plugin's minimum WP requirement is WP 4.4 which allows you to take advantage of the modern way of doing things, while bbPress is still supporting WP 3.6 which means that they have to use outdated practices to maintain backward compatibility.

**Comment by jfarthing84** [comment]
Comparing the language loading of two WordPress plugins is indeed apples to apples. It is the same thing.

If it's incorrect, care to enlighten me on what's changed? And how my logic doesn't "properly" load the language?

**Comment by jrfnl** [comment]
> If it's incorrect, care to enlighten me on what's changed?

You can read up on the relevant changes here: https://make.wordpress.org/plugins/tag/translations/

> And how my logic doesn't "properly" load the language?
1. You are pointing to the wrong directory within your own plugin `languages` vs `language`. Not that that matters much anymore now you are not shipping translations anymore. All the same.
2. You are effectively executing the textdomain loading logic four times instead of twice which would be sufficient - see my PR.
3. You are causing WP to look in the wrong directory (slow) with your last call and WP will load the files from the global directory automatically if you'd only used the proper call in your second call and removed the third.

See:
https://developer.wordpress.org/reference/functions/load_plugin_textdomain/
https://developer.wordpress.org/reference/functions/load_textdomain/

I already send in the PR which does things properly & efficiently, but you choose to close it instead...

**Comment by jfarthing84** [comment]
The link is not really relevant to the loading of translations, unless I missed something...

The functions `load_text_domain` and `load_plugin_textdomain` haven't changed since 3.0 and 2.9 respectively, so I don't see where the "modern way of doing things" statement comes from.
1. The `language` directory has been renamed to `languages`.
2. Fair enough - though the function short-circuits if the files doesn't exist.
3. You are correct here. It appears it would first search directly in `WP_PLUGIN_DIR`. However, I took this approach according to the most recent bbPress source - thinking that an "official" WordPress plugin may have best practices in mind. Maybe I was wrong...

I the end, the langauge is loaded, no?

**Comment by jrfnl** [comment]
> The functions load_text_domain and load_plugin_textdomain haven't changed since 3.0 and 2.9 respectively, so I don't see where the "modern way of doing things" statement comes from.

Seriously ? That was when the _filters_ were introduced. Not when the functions were last changed. Last relevant change for the `load_plugin_textdomain()` call was in 2013 / WP 3.7 when the automatic loading of the plugin translation files for the WP_LANG_DIR was introduced.

As bbPress still supports WP3.6, they can't count on that functionality being there. As TML has a minimum requirement of WP4.4, _you_ can.

> The link is not really relevant to the loading of translations, unless I missed something...

You are. Previously - as in up to about four months ago - it was rare for WP_LANG_DIR translations to be available. Now it is common as WP.org loaded in all existing translations from plugins. As translations are "shared" within GlotPress up to a point, that also means new translations will be easier to create and available quicker - independently of new plugin releases.

> The language directory has been renamed to languages.

It wasn't renamed (yet) in 6.4.3 in which you released your patch for this issue or if it was, I suggest you check your SVN uploading as it didn't come through in the wp.org repo.
Considering the directory rename, this also means that the `Domain Path: /language` bit of the plugin header has to be corrected as it has to be in sync.

> ... thinking that an "official" WordPress plugin may have best practices in mind. Maybe I was wrong...

Quite often these are side projects for which people are given little time, so no, unfortunately you can't.
Don't get me started on JetPack in that respect... one of the worst examples of a plugin & coding practices if ever I saw one....

**Comment by jfarthing84** [comment]
Consider me enlightened. What is considered the "standard" directories for storing translations - or where to people like to keep them? Do I even need to support the custom `wp-content/languages/theme-my-login` location?

**Comment by jrfnl** [comment]
>  What is considered the "standard" directories for storing translations - or where to people like to keep them?

Any subdirectory within your WP install, most often it will be one called `languages`, `language` or `lang`. As long as you indicate the right directory in the `load_plugin_textdomain()` call + in the plugin header `Domain Path:` (for compatibility with GlotPress read in), the actual name of the directory does not matter that much.

Though taking the recent changes into account and considering the minimum requirement for TML is WP 4.4, you don't actually need to store translations in your plugin anymore. Just the .pot file should be sufficient.

> Do I even need to support the custom wp-content/languages/theme-my-login location?

I'd say _yes_ for backward compatibility. As the possibility to use that directory was (is) a documented feature of the plugin, removing support for it could have quite an impact for those people who've been using it to customize the language strings for their site.

The filter I used in my PR is specifically for these kind of situations, which is of course why I adjusted the code to use it.

**Pull request closed without merging**
