### PR TITLE
No need to pass objects by reference since PHP5

### PR DESCRIPTION
**Pull request by jrfnl**
Ref: http://php.net/manual/en/language.oop5.references.php

### CODE REVIEW

**Comment by jfarthing84** [comment]
No periods at the end of commit messages, please.

**Comment by jrfnl** [comment]
Seriously ?

**Comment by jfarthing84** [comment]
Yes.

**Comment by jrfnl** [comment]
If you're that strict, we may want to have a discussion on applying the WP coding standards too....

Anyway, PR should be ok now.

**Pull request merged**
